LIBRETRO_DEPS_DIR    = $(CORE_DIR)/deps
LIBRETRO_COMM_DIR    = $(LIBRETRO_DEPS_DIR)/libretro-common
LIBOGG_DIR           = $(LIBRETRO_DEPS_DIR)/libogg
LIBVORBIS_DIR        = $(LIBRETRO_DEPS_DIR)/libvorbis

INCFLAGS :=  \
	-I$(CORE_DIR)/src \
	-I$(LIBOGG_DIR)/include \
	-I$(LIBVORBIS_DIR)/include \
	-I$(LIBVORBIS_DIR)/lib \
	-I$(LIBRETRO_COMM_DIR)/include

SOURCES_CXX :=\
	$(CORE_DIR)/src/archive.cpp \
	$(CORE_DIR)/src/archivezip.cpp \
	$(CORE_DIR)/src/audio.cpp \
	$(CORE_DIR)/src/bios.cpp \
	$(CORE_DIR)/src/cdrom.cpp \
	$(CORE_DIR)/src/cdromcontroller.cpp \
	$(CORE_DIR)/src/cdromtoc.cpp \
	$(CORE_DIR)/src/chdfile.cpp \
	$(CORE_DIR)/src/datapacker.cpp \
	$(CORE_DIR)/src/file.cpp \
	$(CORE_DIR)/src/flacfile.cpp \
	$(CORE_DIR)/src/input.cpp \
	$(CORE_DIR)/src/lc8951.cpp \
	$(CORE_DIR)/src/libretro_backupram.cpp \
	$(CORE_DIR)/src/libretro_bios.cpp \
	$(CORE_DIR)/src/libretro_common.cpp \
	$(CORE_DIR)/src/libretro_input.cpp \
	$(CORE_DIR)/src/libretro_log.cpp \
	$(CORE_DIR)/src/libretro_memmap.cpp \
	$(CORE_DIR)/src/libretro_variables.cpp \
	$(CORE_DIR)/src/libretro.cpp \
	$(CORE_DIR)/src/m68kintf.cpp \
	$(CORE_DIR)/src/memory_backupram.cpp \
	$(CORE_DIR)/src/memory_cdintf.cpp \
	$(CORE_DIR)/src/memory_input.cpp \
	$(CORE_DIR)/src/memory_mapped.cpp \
	$(CORE_DIR)/src/memory_paletteram.cpp \
	$(CORE_DIR)/src/memory_switches.cpp \
	$(CORE_DIR)/src/memory_video.cpp \
	$(CORE_DIR)/src/memory_z80comm.cpp \
	$(CORE_DIR)/src/memory.cpp \
	$(CORE_DIR)/src/neogeocd.cpp \
	$(CORE_DIR)/src/oggfile.cpp \
	$(CORE_DIR)/src/path.cpp \
	$(CORE_DIR)/src/timeprofiler.cpp \
	$(CORE_DIR)/src/timer.cpp \
	$(CORE_DIR)/src/timergroup.cpp \
	$(CORE_DIR)/src/video.cpp \
	$(CORE_DIR)/src/wavfile.cpp \
	$(CORE_DIR)/src/z80intf.cpp

SOURCES_CXX += \
	${CORE_DIR}/src/3rdparty/ym/ym2610.cpp \
	${CORE_DIR}/src/3rdparty/z80/z80.cpp \
	${CORE_DIR}/src/3rdparty/z80/z80daisy.cpp

SOURCES_C := \
	$(CORE_DIR)/src/3rdparty/musashi/m68kcpu.c \
	$(CORE_DIR)/src/3rdparty/musashi/m68kops.c \
	$(CORE_DIR)/src/3rdparty/musashi/softfloat/softfloat.c

# libretro-common. The CD image reader (rchd), the Vorbis, FLAC and WAV
# decoders and the zip/deflate/lzma/zstd primitives all live here now:
# libchdr, libogg, libvorbis, minizip and the zlib, LZMA and zstd copies
# that came bundled with libchdr are gone.
SRC_LIBRETRO_COMMON = \
	$(LIBRETRO_COMM_DIR)/compat/compat_posix_string.c \
	$(LIBRETRO_COMM_DIR)/compat/compat_strcasestr.c \
	$(LIBRETRO_COMM_DIR)/compat/compat_strl.c \
	$(LIBRETRO_COMM_DIR)/compat/fopen_utf8.c \
	$(LIBRETRO_COMM_DIR)/encodings/encoding_crc32.c \
	$(LIBRETRO_COMM_DIR)/encodings/encoding_deflate.c \
	$(LIBRETRO_COMM_DIR)/encodings/encoding_huffman.c \
	$(LIBRETRO_COMM_DIR)/encodings/encoding_rzstd.c \
	$(LIBRETRO_COMM_DIR)/encodings/encoding_utf.c \
	$(LIBRETRO_COMM_DIR)/features/features_cpu.c \
	$(LIBRETRO_COMM_DIR)/file/archive_file.c \
	$(LIBRETRO_COMM_DIR)/file/archive_file_zlib.c \
	$(LIBRETRO_COMM_DIR)/file/file_path_io.c \
	$(LIBRETRO_COMM_DIR)/file/file_path.c \
	$(LIBRETRO_COMM_DIR)/file/retro_dirent.c \
	$(LIBRETRO_COMM_DIR)/formats/7z/r7z_lzma.c \
	$(LIBRETRO_COMM_DIR)/formats/chd/rchd.c \
	$(LIBRETRO_COMM_DIR)/formats/flac/rflac.c \
	$(LIBRETRO_COMM_DIR)/formats/vorbis/rvorbis.c \
	$(LIBRETRO_COMM_DIR)/formats/wav/rwav.c \
	$(LIBRETRO_COMM_DIR)/lists/dir_list.c \
	$(LIBRETRO_COMM_DIR)/lists/file_list.c \
	$(LIBRETRO_COMM_DIR)/lists/string_list.c \
	$(LIBRETRO_COMM_DIR)/memmap/memalign.c \
	$(LIBRETRO_COMM_DIR)/streams/file_stream.c \
	$(LIBRETRO_COMM_DIR)/string/stdstring.c \
	$(LIBRETRO_COMM_DIR)/time/rtime.c \
	$(LIBRETRO_COMM_DIR)/vfs/vfs_implementation.c

ifeq ($(HAVE_CDROM), 1)
SRC_LIBRETRO_COMMON += \
	 $(LIBRETRO_COMM_DIR)/cdrom/cdrom.c \
	 $(LIBRETRO_COMM_DIR)/vfs/vfs_implementation_cdrom.c
endif

SOURCES_C += \
	$(LIBOGG_DIR)/src/bitwise.c \
	$(LIBOGG_DIR)/src/framing.c

SOURCES_C += \
	$(LIBVORBIS_DIR)/lib/bitrate.c \
	$(LIBVORBIS_DIR)/lib/block.c \
	$(LIBVORBIS_DIR)/lib/codebook.c \
	$(LIBVORBIS_DIR)/lib/envelope.c \
	$(LIBVORBIS_DIR)/lib/floor0.c \
	$(LIBVORBIS_DIR)/lib/floor1.c \
	$(LIBVORBIS_DIR)/lib/info.c \
	$(LIBVORBIS_DIR)/lib/lookup.c \
	$(LIBVORBIS_DIR)/lib/lpc.c \
	$(LIBVORBIS_DIR)/lib/lsp.c \
	$(LIBVORBIS_DIR)/lib/mapping0.c \
	$(LIBVORBIS_DIR)/lib/mdct.c \
	$(LIBVORBIS_DIR)/lib/psy.c \
	$(LIBVORBIS_DIR)/lib/registry.c \
	$(LIBVORBIS_DIR)/lib/res0.c \
	$(LIBVORBIS_DIR)/lib/sharedbook.c \
	$(LIBVORBIS_DIR)/lib/smallft.c \
	$(LIBVORBIS_DIR)/lib/synthesis.c \
	$(LIBVORBIS_DIR)/lib/vorbisfile.c \
	$(LIBVORBIS_DIR)/lib/window.c

ifneq ($(STATIC_LINKING),1)
SOURCES_C +=	$(SRC_LIBRETRO_COMMON)
endif
